name: Unity Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # リポジトリをチェックアウト
    - uses: actions/checkout@v4
      with:
        lfs: true

    # Unityライブラリのキャッシュ
    - uses: actions/cache@v4
      with:
        path: Library
        key: Library-ubuntu-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-ubuntu-

    # Unityテストの実行
    - name: Run Unity Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: .
        unityVersion: 2022.3.42f1
        testMode: EditMode
        artifactsPath: test-results
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    # テスト結果のアップロード
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results
