name: Unity Tests on Self-Hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_EDITOR_PATH: C:\Users\ryu19\opt\unity\2022.3.42f1\Editor\Unity.exe

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    # リポジトリをチェックアウト
    - uses: actions/checkout@v4

    # Unityライブラリのキャッシュ
    - uses: actions/cache@v4
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    # Unityテストの実行
    - name: Run Unity Tests
      run: |
        "%UNITY_EDITOR_PATH%" -quit -batchmode -projectPath "${{ github.workspace }}" -runTests -testPlatform EditMode -testResults "test-results.xml"
      shell: cmd

    # テスト結果のアップロード
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
